const facts = [
  "The shortest war in history was between Britain and Zanzibar in 1896. It lasted just 38 minutes.",
  "The world's largest snowflake on record measured 15 inches wide and 8 inches thick.",
  "The fingerprints of a koala are so indistinguishable from humans that they have on occasion been confused at a crime scene.",
  "The world's largest snow maze is in Warren, Vermont, and covers over 2,500 square feet.",
  "The first computer mouse was invented by Douglas Engelbart in 1963.",
  "The highest temperature ever recorded on Earth was 134 degrees Fahrenheit (56.7 degrees Celsius) in Death Valley, California, in 1913.",
  "If you sneeze too hard, you can fracture a rib.", 
  "A group of flamingos is called a flamboyance.", 
  "A small child could swim through the veins of a blue whale.", 
  "The world's oldest piece of chewing gum is over 9,000 years old.", 
  "Penguins have an organ above their eyes that converts seawater into freshwater.", 
  "The world's largest grand piano was built by a 15-year-old in New Zealand.", 
  "Cows have best friends and become stressed when they are separated.", 
  "The first recorded use of the word 'nerd' was in Dr. Seuss's book 'If I Ran the Zoo'.", 
  "The human nose can detect over 1 trillion different scents.",
  "In Japan, it is common to have a 'lonely death' which means someone dies alone and is not discovered for a long period of time.", 
  "Sloths only defecate once a week.", 
  "There are more possible iterations of a game of chess than there are atoms in the known universe.",
  "A group of ferrets is called a business.", 
  "Octopuses have three hearts.",
  "Honey never spoils.",
  "Bananas are berries but strawberries are not.",
  "The shortest commercial flight in the world is only 57 seconds long.", 
  "Ketchup was sold as medicine in the 1830s.", 
  "Some turtles can breathe through their butts.", 
  "Pineapples take two years to grow.", 
  "The longest wedding veil was longer than 63 football fields.", 
  "A baby octopus is about the size of a flea at birth.",
  "The first oranges weren't actually orange, but green.",
  "A cockroach can live for several weeks without its head.",
  "The world's largest swimming pool is over 1,000 meters long and contains over 250 million liters of water.", ,
  "The world's largest collection of rubber ducks contains over 5,000 rubber ducks and is located in the United States.",
  "The oldest living thing in the world is a tree in Sweden that is over 9,500 years old.", 
  "The longest word in the English language has 189,819 letters and takes over 3 hours to pronounce.",
  "The world's largest rubber band ball weighs over 4,000 pounds and is over 6 feet tall.", 
  "In Switzerland, it is illegal to own just one guinea pig because they get lonely.",
  "The world's largest jigsaw puzzle has over 500,000 pieces and takes over 17 weeks to complete.",
  "There is a species of bird called the bar-tailed godwit that can fly over 7,000 miles without stopping.",
  "The world's largest collection of pizza boxes contains over 595 boxes and is located in the United States.",
  "The Grand Theft Auto franchise has lawsuits that total over $1 billion.",
  "The eye of an ostrich is bigger than its brain.",
  "On average, a secretary will use its left hand for 56% of what they type on a keyboard.",
  "Japan has 23 vending machines per person.",
  "Sign language has tongue twisters.",
  "April 11, 1954, was recorded as the most boring day in the world.",
  "Sailors working for the Royal Navy need special permission to grow their beards.",
  "There are fewer stars than there are trees on Earth.",
  "75 burgers are sold in McDonald’s every second.",
  "The most widely printed book in the world is the catalog for IKEA.",
  "There are more than 200 flavors of Kit Kat in Japan.",
  "Great Britain once had a number where you can report rogue traffic cones.",
  "The largest living organism is an aspen grove.",
  "Kummerspeck is German for the weight gained during emotional eating.",
  "Bottled water has an expiration date.",
  "Monty Python has one of the most requested songs for funerals in England.",
  "The world’s most successful pirate was a woman.",
  "Cacti come in many different colors other than green.",
  "Bananas are not only yellow.",
  "More people speak English as their second language than those who use it as their mother tongue.",
  "Triskaidekaphobia is the fear of the number 13.",
  "The opposite sides of dice will always equal 7.",
  "The average adult spends more time on the toilet than exercising.",
  "About 7% of American adults believe chocolate milk comes from brown cows.",
  "Bananas get their curved shape by growing towards the sun.",
  "Alaska is the only state whose name is on a single row on the keyboard.",
  "123456 is the most common password.",
  "The average American spends 2.5 days annually looking for lost items.",
  "More monopoly money is printed annually rather than actual currency.",
  "The Antarctic glaciers are made up of 3% penguin urine.",
  "A single strand of spaghetti is individually referred to as spaghetto.",
  "The fat Buddha statue and in pictures is not Buddha himself.",
  "12 plants and 5 animals make up 75% of diets around the world.",
  "The release of Pokemon GO increased game-related accidents by 26.5%.",
];

function generateFact() {
  const factElement = document.getElementById("fact");
  const factBtn = document.getElementById("factBtn");
  const randomIndex = Math.floor(Math.random() * facts.length);
  factElement.innerHTML = facts[randomIndex];
  factBtn.innerHTML = "Generate Another Fact";
}
